### ISSUE TITLE
Authentication always fails with unexpected error

### ISSUE THREAD

**Issue by carguel** [pgina/pgina#246]
Hi, 

I installed PGina on two Windows 7 laptops. It is working correctly on one laptop but never succeeds to authenticate an LDAP user on the other laptop.

The logon screen displays that the Pgina Status is "Connected". After submitting a valid login/password, I get the following error : 

       Unexpected error while syncing user's info: System.Runtime.InteropServices.COMException (0x80070842): The Server service is not started.
    
       at System.DirectoryServices.DirectoryEntry.RefreshCache()
       at System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
       at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
       at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
       at System.DirectoryServices.AccountManagement.PrincipalSearcher.SetDefaultPageSizeForContext()
       at pGina.Plugin.LocalMachine.LocalAccount.GetUserPrincipal(String username)
       at pGina.Plugin.LocalMachine.LocalAccount.CreateOrGetUserPrincipal(UserInformation userInfo)
       at pGina.Plugin.LocalMachine.LocalAccount.SyncToLocalUser()
       at pGina.Plugin.LocalMachine.PluginImpl.AuthenticatedUserGateway(SessionProperties properties)

Here is a snapshot of this error using the simulator : 

![screenshot-pgina](https://cloud.githubusercontent.com/assets/1271572/5980042/e2ebf046-a8ac-11e4-811c-dc1a38e87307.png)

The two laptops have not been installed by the same team. So I suspect an issue in the Windows configuration. The problem occurs on the laptop which should have a more secured configuration, but I did not succeed to identify what could cause this issue.

Thanks for your support.

**Comment by aliask** [comment]
Hi carguel, I am also experiencing this issue - did you have any luck resolving it?

**Comment by carguel** [comment]
Unfortunately, no !
I am still waiting for a reply from the maintainer.

**Comment by carguel** [comment]
@aliask, I finally succeeded to resolve this issue.

Actually, it works with a pgina fork (see MutonUfoAI/pgina#20) but i guess it should work with the upstream pgina.

The solution was simply to start the Windows __server__ service from the Service configuraton panel.
Hope it helps.
