### ISSUE TITLE
pGina 3.2.4 with STARTTLS support 

### ISSUE THREAD

**Issue by pakmav** [pgina/pgina#255]
Hello,

we have a LDAPv3 server using STARTTLS, but when we tried to use pGina 3.2.4 to connect, we obtain this error:

2015-05-27 09:10:38,990 [1|DEBUG] LdapPlugin: BeginChain
2015-05-27 09:10:39,050 [1|DEBUG] LdapServer: Initializing LdapServer host(s): [ldap.uma.es], port: 389, encryption = START_TLS, verifyCert = False
2015-05-27 09:10:39,050 [1|DEBUG] LdapServer: Timeout set to 10 seconds.
2015-05-27 09:10:39,060 [1|DEBUG] LdapServer: Starting TLS...
2015-05-27 09:10:50,378 [1|DEBUG] LdapServer: VerifyCert(...)
2015-05-27 09:10:50,388 [1|DEBUG] LdapServer: Verifying certificate from host: ldap.uma.es
2015-05-27 09:10:50,398 [1|DEBUG] LdapServer: Server certificate accepted without verification.
2015-05-27 09:10:50,398 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Performing login process
2015-05-27 09:10:50,408 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Authenticating user paqui@uma.es, 2 plugins available
2015-05-27 09:10:50,418 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Calling 0f52390b-c781-43ae-bd62-553c77fa4cf7
2015-05-27 09:10:50,418 [1|DEBUG] LdapPlugin: AuthenticateUser(ff179424-67bd-4842-b058-a3478dc46aa3)
2015-05-27 09:10:50,438 [1|DEBUG] LdapPlugin: Received username: paqui@uma.es
2015-05-27 09:10:50,438 [1|DEBUG] LdapPlugin: Attempting authentication for paqui@uma.es
2015-05-27 09:10:50,468 [1|DEBUG] LdapServer: Attempting bind as ou=lcc.search,idnc=sist,dc=uma,dc=es
2015-05-27 09:10:50,478 [1|DEBUG] LdapServer: Successful bind to ldap.uma.es as ou=lcc.search,idnc=sist,dc=uma,dc=es
2015-05-27 09:10:50,478 [1|DEBUG] LdapServer: Searching for DN using filter irisMailAlternateAddress=paqui@uma.es
2015-05-27 09:10:50,488 [1|DEBUG] LdapServer: Searching context idnc=usr,dc=uma,dc=es
2015-05-27 09:10:50,498 [1|DEBUG] LdapServer: Found DN: idnc=72f4c5cd-c740-49d0-a7dc-8440ffd2a4f2,idnc=usr,dc=uma,dc=es
2015-05-27 09:10:50,508 [1|DEBUG] LdapServer: Attempting to bind with DN idnc=72f4c5cd-c740-49d0-a7dc-8440ffd2a4f2,idnc=usr,dc=uma,dc=es
2015-05-27 09:10:50,508 [1|DEBUG] LdapServer: Attempting bind as idnc=72f4c5cd-c740-49d0-a7dc-8440ffd2a4f2,idnc=usr,dc=uma,dc=es
2015-05-27 09:10:50,508 [1|DEBUG] LdapServer: Successful bind to ldap.uma.es as idnc=72f4c5cd-c740-49d0-a7dc-8440ffd2a4f2,idnc=usr,dc=uma,dc=es
2015-05-27 09:10:50,508 [1|DEBUG] LdapServer: LDAP DN idnc=72f4c5cd-c740-49d0-a7dc-8440ffd2a4f2,idnc=usr,dc=uma,dc=es successfully bound to server, return success
2015-05-27 09:10:50,518 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: 0f52390b-c781-43ae-bd62-553c77fa4cf7 Succeeded
2015-05-27 09:10:50,528 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Calling 12fa152d-a2e3-4c8d-9535-5dcd49dfcb6d
2015-05-27 09:10:50,558 [1|DEBUG] LocalMachine: AuthenticateUser(ff179424-67bd-4842-b058-a3478dc46aa3)
2015-05-27 09:10:50,558 [1|DEBUG] LocalMachine: Found username: paqui@uma.es
2015-05-27 09:10:50,568 [1|INFO ] LocalMachine: Authenticated user: paqui@uma.es
2015-05-27 09:10:50,568 [1|DEBUG] LocalMachine: AuthenticateUser: Mirroring group membership from SAM
2015-05-27 09:10:50,698 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: 12fa152d-a2e3-4c8d-9535-5dcd49dfcb6d Succeeded
2015-05-27 09:10:50,698 [1|INFO ] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Successfully authenticated paqui@uma.es
2015-05-27 09:10:50,708 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Authorizing user paqui@uma.es, 1 plugins available
2015-05-27 09:10:50,708 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Calling 12fa152d-a2e3-4c8d-9535-5dcd49dfcb6d
2015-05-27 09:10:50,748 [1|INFO ] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Successfully authorized paqui@uma.es
2015-05-27 09:10:50,758 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Processing gateways for user paqui@uma.es, 1 plugins available
2015-05-27 09:10:50,758 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Calling 12fa152d-a2e3-4c8d-9535-5dcd49dfcb6d
2015-05-27 09:10:50,778 [1|DEBUG] LocalMachine: AuthenticatedUserGateway(ff179424-67bd-4842-b058-a3478dc46aa3) for user: paqui@uma.es
2015-05-27 09:10:50,788 [1|DEBUG] LocalAccount[paqui@uma.es]: SyncToLocalUser()
2015-05-27 09:10:50,928 [1|DEBUG] LocalAccount[paqui@uma.es]: Checking for groups to remove.
2015-05-27 09:10:50,960 [1|DEBUG] LocalAccount[paqui@uma.es]: Checking for groups to add
2015-05-27 09:10:50,964 [1|DEBUG] LocalAccount[paqui@uma.es]: End SyncToLocalUser()
2015-05-27 09:10:50,968 [1|INFO ] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Successfully processed gateways for paqui@uma.es
2015-05-27 09:10:50,975 [1|DEBUG] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: End login chain, 1 stateful plugin(s).
2015-05-27 09:10:50,978 [1|DEBUG] LdapPlugin: EndChain
2015-05-27 09:10:50,982 [1|DEBUG] LdapServer: Closing LDAP connection to ldap.uma.es.
2015-05-27 09:10:50,985 [1|DEBUG] LdapServer: Stopping TLS
2015-05-27 09:10:50,992 [1|ERROR] PluginDriver:ff179424-67bd-4842-b058-a3478dc46aa3: Exception during login process: System.DirectoryServices.Protocols.TlsOperationException: The Stop TLS operation failed.
   at System.DirectoryServices.Protocols.LdapSessionOptions.StopTransportLayerSecurity()
   at pGina.Plugin.Ldap.LdapServer.Close()
   at pGina.Core.PluginDriver.EndChain()
   at pGina.Core.PluginDriver.PerformLoginProcess()

The authentication is ok, but when "Stopping TLS" we have this fail. Could you help us?

Thank you!.

**Comment by pakmav** [comment]
Please, could anyone respond? Thank you.

**Comment by MutonUfoAI** [comment]
use a test machine and do it with this release
https://github.com/MutonUfoAI/pgina/releases
I've implemented startTLS a bit differently

**Comment by filipvh** [comment]
Have this same issue
Using modern OpenLDAP with TLS

**Comment by filipvh** [comment]
I would like to fix this, but don't know how? Anyone? More info:
http://imgur.com/a/2bFzt

**Comment by filipvh** [comment]
#311 Hope this solves it... does so for me
