### ISSUE TITLE
Internal error: LdapServer object not available

### ISSUE THREAD

**Issue by rwpucko** [pgina/pgina#260]
Currently trying to install Pgina version 3.1.8.0 on a Windows 64 bit system for an unattended install. I'm able to deploy Pgina scripted using the silent command and then apply my registry settings. 

I'm using the LDAP module, Local Machine, and Single User Login. After i install Pgina and apply the registry key and reboot the system i am unable to log into the computer using Pgina. I receive an error message of "Internal error: LdapServer object not available"

If i open up Pgina and look at the plugins i am unable to see the Single User Login. If i go into the registry and delete the folder which contains  the Single User Login and restart the Pgina client i see the plugin and if i reconfigure the plugin it adds it back into the registry (same as what was originally imported).

It is very strange and i have no idea why it doesn't work as expected. All other plugins seem to work fine, but the single user login has issues. 

Any thoughts? 

--------------------------

Section of Configuration Log:

2015-08-12 16:48:08,026 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.Sample.SimplePlugin from plugin: C:\Program Files\pGina\Plugins\Core\pGina.Plugin.Sample.dll uuid: 16fc47c0-f17b-4d99-a820-edbf0b0c764a
2015-08-12 16:48:08,042 [2120|1|DEBUG] SessionLimitPlugin: Plugin initialized on NEW-VMWARE-42 in PID: 2120 Session: 1
2015-08-12 16:48:08,042 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.SessionLimit.PluginImpl from plugin: C:\Program Files\pGina\Plugins\Core\pGina.Plugin.SessionLimit.dll uuid: d73131d7-7af2-47bb-bbf4-4f8583b44962
2015-08-12 16:48:08,057 [2120|1|ERROR] PluginLoader: Error loading C:\Program Files\pGina\Plugins\Core\pGina.Plugin.SingleUser.dll: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'pGina.Plugin.SingleUser.Settings' threw an exception. ---> System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Abstractions.Settings.DynamicSettings.SetDefaultEncryptedSetting(String name, String value, Byte[] optionalEntropy)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at pGina.Plugin.SingleUser.Settings.Init()
   at pGina.Plugin.SingleUser.Settings..cctor()
   --- End of inner exception stack trace ---
   at pGina.Plugin.SingleUser.Settings.Init()
   at pGina.Plugin.SingleUser.PluginImpl..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at pGina.Core.PluginLoader.LoadPluginsFromDir(String dir)
2015-08-12 16:48:08,057 [2120|1|DEBUG] PluginLoader: Loading plugins from C:\Program Files\pGina\Plugins\Contrib
2015-08-12 16:48:08,073 [2120|1|DEBUG] EmailAuthPlugin: Plugin initialized on NEW-VMWARE-42 in PID: 2120 Session: 1
2015-08-12 16:48:08,073 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.Email.EmailAuthPlugin from plugin: C:\Program Files\pGina\Plugins\Contrib\pGina.Plugin.Email.dll uuid: ec3221a6-621f-44ce-b77b-e074298d6b4e
2015-08-12 16:48:08,073 [2120|1|DEBUG] RADIUSPlugin: Plugin initialized on NEW-VMWARE-42 in PID: 2120 Session: 1
2015-08-12 16:48:08,073 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.RADIUS.RADIUSPlugin from plugin: C:\Program Files\pGina\Plugins\Contrib\pGina.Plugin.RADIUSPlugin.dll uuid: 350047a0-2d0b-4e24-9f99-16cd18d6b142
2015-08-12 16:48:08,088 [2120|1|DEBUG] UsernameModPlugin: Plugin initialized on NEW-VMWARE-42 in PID: 2120 Session: 1
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.UsernameMod.UsernameModPlugin from plugin: C:\Program Files\pGina\Plugins\Contrib\pGina.Plugin.UsernameMod.dll uuid: 98477b3a-830d-4bee-b270-2d7435275f9c
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader: Plugins loaded, list follows: 
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader:   LDAP -> 0f52390b-c781-43ae-bd62-553c77fa4cf7
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader:   Local Machine -> 12fa152d-a2e3-4c8d-9535-5dcd49dfcb6d
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader:   MySQL -> a89df410-53ca-4fe1-a6ca-4479b841ca19
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader:   MySQL Logger -> b68cf064-9299-4765-ac08-acb49f93f892
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader:   Simple Demonstration -> 16fc47c0-f17b-4d99-a820-edbf0b0c764a
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader:   Session Limit -> d73131d7-7af2-47bb-bbf4-4f8583b44962
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader:   Email Authentication -> ec3221a6-621f-44ce-b77b-e074298d6b4e
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader:   RADIUS Plugin -> 350047a0-2d0b-4e24-9f99-16cd18d6b142
2015-08-12 16:48:08,088 [2120|1|DEBUG] PluginLoader:   Modify Username Plugin -> 98477b3a-830d-4bee-b270-2d7435275f9c
2015-08-12 16:48:09,912 [2120|1|DEBUG] PluginLoader: Loading plugins from C:\Program Files\pGina\Plugins\Core
2015-08-12 16:48:09,912 [2120|1|DEBUG] LdapPlugin: LDAP Plugin initialized on NEW-VMWARE-42 in PID: 2120 Session: 1
2015-08-12 16:48:09,912 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.Ldap.LdapPlugin from plugin: C:\Program Files\pGina\Plugins\Core\pGina.Plugin.Ldap.dll uuid: 0f52390b-c781-43ae-bd62-553c77fa4cf7
2015-08-12 16:48:09,912 [2120|1|DEBUG] LocalMachine: Plugin initialized on NEW-VMWARE-42 in PID: 2120 Session: 1
2015-08-12 16:48:09,912 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.LocalMachine.PluginImpl from plugin: C:\Program Files\pGina\Plugins\Core\pGina.Plugin.LocalMachine.dll uuid: 12fa152d-a2e3-4c8d-9535-5dcd49dfcb6d
2015-08-12 16:48:09,912 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.MySQLAuth.PluginImpl from plugin: C:\Program Files\pGina\Plugins\Core\pGina.Plugin.MySQLAuth.dll uuid: a89df410-53ca-4fe1-a6ca-4479b841ca19
2015-08-12 16:48:09,912 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.MySqlLogger.PluginImpl from plugin: C:\Program Files\pGina\Plugins\Core\pGina.Plugin.MySqlLogger.dll uuid: b68cf064-9299-4765-ac08-acb49f93f892
2015-08-12 16:48:09,912 [2120|1|DEBUG] SimplePlugin: Plugin initialized on NEW-VMWARE-42 in PID: 2120 Session: 1
2015-08-12 16:48:09,912 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.Sample.SimplePlugin from plugin: C:\Program Files\pGina\Plugins\Core\pGina.Plugin.Sample.dll uuid: 16fc47c0-f17b-4d99-a820-edbf0b0c764a
2015-08-12 16:48:09,912 [2120|1|DEBUG] SessionLimitPlugin: Plugin initialized on NEW-VMWARE-42 in PID: 2120 Session: 1
2015-08-12 16:48:09,912 [2120|1|DEBUG] PluginLoader: Created plugin object type: pGina.Plugin.SessionLimit.PluginImpl from plugin: C:\Program Files\pGina\Plugins\Core\pGina.Plugin.SessionLimit.dll uuid: d73131d7-7af2-47bb-bbf4-4f8583b44962
2015-08-12 16:48:09,912 [2120|1|ERROR] PluginLoader: Error loading C:\Program Files\pGina\Plugins\Core\pGina.Plugin.SingleUser.dll: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'pGina.Plugin.SingleUser.Settings' threw an exception. ---> System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Abstractions.Settings.DynamicSettings.SetDefaultEncryptedSetting(String name, String value, Byte[] optionalEntropy)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at pGina.Plugin.SingleUser.Settings.Init()
   at pGina.Plugin.SingleUser.Settings..cctor()
   --- End of inner exception stack trace ---
   at pGina.Plugin.SingleUser.Settings.Init()
   at pGina.Plugin.SingleUser.PluginImpl..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at pGina.Core.PluginLoader.LoadPluginsFromDir(String dir)
2015-08-12 16:48:09,912 [2120|1|DEBUG] PluginLoader: Loading plugins from C:\Program Files\pGina\Plugins\Contrib

**Comment by MutonUfoAI** [comment]
2015-08-12 16:48:09,912 [2120|1|ERROR] PluginLoader: Error loading C:\Program Files\pGina\Plugins\Core\pGina.Plugin.SingleUser.dll: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'pGina.Plugin.SingleUser.Settings' threw an exception. ---> System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)


do not import encrypted settings!

**Comment by rwpucko** [comment]
Hans,

I’m attempting to deploy Pgina on our lab image as a post-install task. If I cannot have the password included in the registry file when imported to a newly imaged system how can I get the password included via scripts?

-Bob

**Comment by MutonUfoAI** [comment]
you've found the logical error

I've made a small tool to do that
copy it into the pgina folder (c:\program files\pgina)

binary
https://drive.google.com/file/d/0B-H7i4GwrDdVNE9Yc0JKb090OUE/view?usp=sharing

source
https://github.com/MutonUfoAI/pgina/commit/b7c31fc5039559fd8bd60c714299ae5a957ef62b

Note:
I'm not sure if it does run on your pgina version, but most likely

**Comment by rwpucko** [comment]
Hans,

Thank you for the program, but it doesn’t seem to work. When executing the EXE I get the following error:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or ass
embly 'Abstractions, Version=3.2.4.1, Culture=neutral, PublicKeyToken=null' or o
ne of its dependencies. The system cannot find the file specified.
   at encryptsetting.Program.Main(String[] args)

I’m also not a programmer so the source code does me little good I’m afraid.

-Bob

**Comment by MutonUfoAI** [comment]
i've tried it with 3.1.8.0 and 3.2.4.0 no problem
did you move the file to C:\Program Files\pGina
in this folder there has to be a file called Abstractions.dll

**Comment by rwpucko** [comment]
Hans,

I was finally able to get it to work. Thank you for following up.

I have another question for you. We have a group policy within windows which displays an additional logon prompt for wireless access. When a user’s inputs this information and attempts to log into windows (laptop). It will first log into the wireless and then try to connect to the domain controller. I see the pGina CP does not show the additional wireless logon fields. Do you know if there is a way to enable this feature?

-Bob

**Comment by MutonUfoAI** [comment]
are you talking about this
https://technet.microsoft.com/en-us/magazine/2007.11.cableguy.aspx

a plugin could do that ...

**Comment by rwpucko** [comment]
Yes- the way Windows natively does it is present the user with two logon screens (one for user authentication and the other for wireless).

If I wanted to ask the pGina community if any plugin developers would be interested in working on this problem what would you recommend? I’m not a programmer and don’t have the skillset to write such a plugin.

-Bob

**Comment by MutonUfoAI** [comment]
the stuff is far more complicated than i tough

plap is working only in a domain environment
but pgna doesnt work on a domain machine

you should close this ticket and open another one
explaining your machine- and server-setup

**Comment by rwpucko** [comment]
Hans,

Thanks for the feedback. I will do so!

Have a nice weekend,

Bob
