### ISSUE TITLE
Unable to sync users local group membership: System.DirectoryServices.AccountManagement.PrincipalOperationException: An error (1332) occurred while enumerating the group membership.  The member's SID could not be resolved.

### ISSUE THREAD

**Issue by abhi1038** [pgina/pgina#269]
Unable to sync users local group membership: System.DirectoryServices.AccountManagement.PrincipalOperationException: An error (1332) occurred while enumerating the group membership.  The member's SID could not be resolved.
   at System.DirectoryServices.AccountManagement.SAMMembersSet.IsLocalMember(Byte[] sid)
   at System.DirectoryServices.AccountManagement.SAMMembersSet.MoveNextLocal()
   at System.DirectoryServices.AccountManagement.SAMMembersSet.MoveNext()
   at System.DirectoryServices.AccountManagement.PrincipalCollectionEnumerator.MoveNext()
   at System.DirectoryServices.AccountManagement.PrincipalCollection.ContainsEnumTest(Principal principal)
   at System.DirectoryServices.AccountManagement.PrincipalCollection.Add(Principal principal)
   at pGina.Plugin.LocalMachine.LocalAccount.SyncToLocalUser()

Can you someone suggest me how to fix this issue? 

![unnamed](https://cloud.githubusercontent.com/assets/5114412/11415088/0bd1cc34-9424-11e5-890b-8c2ced45ac21.jpg)

**Comment by MutonUfoAI** [comment]
An error (1332) occurred while enumerating the group membership. The member's SID could not be resolved.

are you using sid numbers for group names in localmachine plugin
if so, use realnames only (Administrators instead of S-1-5-32-544)
no support for sid2name in localmachine plugin

**Comment by abhi1038** [comment]
No i am not using sid in local machine i am using the real name but still
it throws this error all my windows 7 enterprise are working well only
windows 10 is having this issue.

**Comment by nate-yocom** [comment]
smells like a windows 10 interop bug

**Comment by maheshmadhyastha7** [comment]
Same issue for me too.Can anyone help me in this?

**Comment by maheshmadhyastha7** [comment]
![screenshot-1](https://cloud.githubusercontent.com/assets/12908773/18266058/67a33bf4-7436-11e6-816f-3610c578c6e4.png)

**Comment by maheshmadhyastha7** [comment]
Its alarming issue in as no user can login .

**Comment by mjj29** [comment]
Hi, I'm seeing this on win2019 when logging in via LDAP, is it related?
![image](https://user-images.githubusercontent.com/9658120/136376562-fffad4ad-9efa-4eee-ae22-9aadc9fcaf74.png)

**Comment by mjj29** [comment]
For this one some users can log in, but not all of them
