### ISSUE TITLE
Drive mappings not restored after password change

### ISSUE THREAD

**Issue by legolas108** [pgina/pgina#273]
Hi

Installed pGina 3.2.4.0 on Win10Pro client and authenticating against OpenLDAP 2.4.41-9.5, SSSD 1.11.5.1-7.1 and Samba 4.2.4-6.3 on openSUSE 42.1 Leap. Samba is configured as PDC with the OpenLDAP server as backend.

Works fine except for one issue: when Win user changes their password from the Ctrl+Alt+Del menu, and logs off and on again with that new password, drive mappings won't be restored. The log file says,
"DriveMapper: [...] Failed to map drive \\svr1\Share: invalid username or password. [...] Win32 error code: 1326".
Going back to previous password makes drive mappings work again. Changing password in YaST User and Group Management module instead, makes drive mappings work as expected. So, something YaST User and Group Management must do in addition to what pGina does that makes password changes take effect properly. Tried to clear the SSSD cache also with "sss_cache -E" after Win password change, but doesn't make a difference.

What could be the cause (and resolution)?

Thanks a lot for any hint!
Ole

**Comment by greeneg** [comment]
Sounds a lot like pgina, or at least Windows authentication layer isn't talking to the server in a way to make this work correctly. Getting a wire capture of the dialogue between the two machines would likely help the devs of pgina with debugging this scenario.

**Comment by legolas108** [comment]
Thanks a bunch for speedy reply! Attached a Wireshark capture of a logon with working drive mappings, password change, logoff, and logon with new password and drive mappings not restored.

Should this rather go to a formal bug report?

[test.pcapng.gz](https://github.com/pgina/pgina/files/59868/test.pcapng.gz)

**Comment by legolas108** [comment]
Turns out, after user changed their password on Win, when manually changing their Samba password on the server with smbpasswd, drive mappings appear as expected.

Don't know if pGina is able to determine if it's authenticating against a Samba server and should also update Samba password when Win password is changed. Would of course be convenient.

**Comment by MutonUfoAI** [comment]
possible you need to set more attribs ?
http://mutonufoai.github.io/pgina/documentation/plugins/ldap.html#change_password

Find out what you need to change in samba 4

**Comment by legolas108** [comment]
Yes, wasn't aware of this option - thanks! Added the sambaNTPassword and sambaLMPassword attributes with NT Hash encryption to the already present userPassword attribute, but couldn't add sambaPwdLastSet because the "Timestamp sec..." method isn't available in the 3.2.4.0 pGina version.

When now trying to change the password it says, "Error in LDAP plugin", and the log file says:

2015-12-15 07:28:31,013 [2960|27|DEBUG] LdapServer: LDAP DN uid=Green,ou=people,dc=EXAMPLE,dc=COM successfully bound to server, return success
...
2015-12-15 07:28:31,122 [2960|27|DEBUG] LdapPlugin: Setting attribute sambaNTPassword using hash method NT Hash (sambaNTPassword, MD4)
2015-12-15 07:28:31,138 [2960|27|ERROR] LdapPlugin: Exception in ChangePassword: System.DirectoryServices.Protocols.DirectoryOperationException: The user has insufficient access rights.
   at System.DirectoryServices.Protocols.LdapConnection.ConstructResponse(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeOut, Boolean exceptionOnTimeOut)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at pGina.Plugin.Ldap.LdapPlugin.ChangePassword(ChangePasswordInfo cpInfo, ChangePasswordPluginActivityInfo pluginInfo)
2015-12-15 07:28:31,154 [2960|27|DEBUG] pGina.Service.Impl: ChangePassword: result from 0f52390b-c781-43ae-bd62-553c77fa4cf7 is False message: Error in LDAP plugin.

So it seems a matter of granting each user write permission on their LDAP attributes. Started to get into that but seems to be fairly complex, so need some time...

**Comment by legolas108** [comment]
Finally found time to work on this again. After changing LDAP permissions so each user can modify their own LDAP password attributes, and adding the sambaNTPassword with NTLM method to the list of attributes on the Change Password tab of the LDAP plugin configuration panel the problem is largely resolved.

Only thing left is: on the [LDAP Plugin Documentation page for v. 3.2.0] (http://mutonufoai.github.io/pgina/documentation/plugins/ldap.html) one can also select an LM Hash method for the sambaLMPassword attribute, and a Timestamp method for the sambaPwdLastSet attribute. But these methods are not shown any more in the 3.2.4.1 version. Wouldn't it be good to maintain these attributes, too, and how to do it in the latest 3.2.4.1 version?

Thanks in advance for any hint!

**Comment by MutonUfoAI** [comment]
you are mixing pgina and pgina fork
pgina 3.2.4.1 doesnt own these attribs
while
pgina fork does

**Comment by nate-yocom** [comment]
though i'm interested in bringing this back to pgina mainline for sure.  marking as feature for future milestone
