### ISSUE TITLE
Unable to Verify SSL certificate with LDAP plugin

### ISSUE THREAD

**Issue by akaMoses** [pgina/pgina#287]
Hey,
I've tried to use the "Verify Server Certificate" feature with no success. I've provided the PEM file and I'm always getting the same error: "Internal Error: LdapServer object not available" 
When I'm removing the path to the PEM file, I'm getting the error: "Failed to connect LDAP server"
Here are the errors from the log:

> ****
> **** Simulated login starting: Thursday, February 25, 2016 12:31:56 PM
> **** pGina Version:  3.1.8.0
> **** Enabled plugins: 
> ****     Authentication: LDAP
> ****     Authorization: 
> ****     Gateway: LDAP, Local Machine
> ****     Notification: 
> ****
> 2016-02-25 12:31:56,984 [1|DEBUG] PluginDriver:9119ea34-9e87-4bfe-9c79-e5bc45ef256a: New PluginDriver created
> 2016-02-25 12:31:56,984 [1|DEBUG] PluginDriver:9119ea34-9e87-4bfe-9c79-e5bc45ef256a: Begin login chain, 1 stateful plugin(s).
> 2016-02-25 12:31:56,984 [1|DEBUG] LdapPlugin: BeginChain
> 2016-02-25 12:31:56,984 [1|DEBUG] LdapServer: Loading server certificate: C:\Windows\security\mydomain-com.pem
> 2016-02-25 12:31:56,984 [1|ERROR] LdapPlugin: Failed to create LdapServer: System.Security.Cryptography.CryptographicException: Cannot find the requested object.
> 
>    at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
>    at System.Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
>    at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
>    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName)
>    at pGina.Plugin.Ldap.LdapServer..ctor()
>    at pGina.Plugin.Ldap.LdapPlugin.BeginChain(SessionProperties props)
> 2016-02-25 12:31:56,984 [1|DEBUG] PluginDriver:9119ea34-9e87-4bfe-9c79-e5bc45ef256a: Performing login process
> 2016-02-25 12:31:56,984 [1|DEBUG] PluginDriver:9119ea34-9e87-4bfe-9c79-e5bc45ef256a: Authenticating user testuser, 1 plugins available
> 2016-02-25 12:31:56,984 [1|DEBUG] PluginDriver:9119ea34-9e87-4bfe-9c79-e5bc45ef256a: Calling 0f52390b-c781-43ae-bd62-553c77fa4cf7
> 2016-02-25 12:31:56,984 [1|WARN ] PluginDriver:9119ea34-9e87-4bfe-9c79-e5bc45ef256a: 0f52390b-c781-43ae-bd62-553c77fa4cf7 Failed with Message: Internal error: LdapServer object not available
> 2016-02-25 12:31:56,984 [1|ERROR] PluginDriver:9119ea34-9e87-4bfe-9c79-e5bc45ef256a: Failed to authenticate testuser, Message: Internal error: LdapServer object not available
> 2016-02-25 12:31:56,984 [1|DEBUG] PluginDriver:9119ea34-9e87-4bfe-9c79-e5bc45ef256a: End login chain, 1 stateful plugin(s).
> 2016-02-25 12:31:56,984 [1|DEBUG] LdapPlugin: EndChain
> 

Thanks in advance,
Moses

**Comment by akaMoses** [comment]
Which SSL ciphers pGina supports?

**Comment by MutonUfoAI** [comment]
add the cert issuer to th local machine certstore
its exact the same way as in xp
http://www.dartmouth.edu/~deploypki/materials/web_authn/pages/IISonXP_AddingTrustedCACertToComputer.htm
