### ISSUE TITLE
PluginLoader XmlSerializers Resolve Dependency

### ISSUE THREAD

**Issue by mdghost** [pgina/pgina#295]
I use my own plugin and he has a XmlSerializers which is generated on the fly by GAC_MSIL.
It doesn't metter if I put my own myAssambly.XmlSerializers.dll to $pGina\Plugins\Contrib next to myAssambly.dll because it is some kind of anonymous reqest from .NET, so requestorPath is wrong. After that the XmlSerializers from GAC_MSIL folder try to load again myAssambly.dll and the requestorPath is diferent then myAssambly.dll path. I think the best way is skip resolving from and for XmlSerializers like you do it for '.resources' files.
http://stackoverflow.com/questions/1127431/xmlserializer-giving-filenotfoundexception-at-constructor

Nowadays I walkaround it by catch that FileLoadException and call again my AuthenticateUser() method. It works beacause GAC_MSIL has just created myAssambly.XmlSerializers.dll in his folder. But the logon process is a little bit longer than it should be.
```
****
**** Simulated login starting: 28 kwietnia 2016 13:59:56
**** pGina Version:  3.2.4.1
**** Enabled plugins: 
****     Authentication: vCRM Authentication, Local Machine
****     Authorization: vCRM Authentication, Local Machine
****     Gateway: Local Machine
****     Notification: MyWS Logger
****
2016-04-28 13:59:56,229 [1|DEBUG] PluginDriver:9583f9eb-3bc6-4c7f-8812-b596770a8493: New PluginDriver created
2016-04-28 13:59:56,242 [1|DEBUG] PluginDriver:9583f9eb-3bc6-4c7f-8812-b596770a8493: Begin login chain, 0 stateful plugin(s).
2016-04-28 13:59:56,243 [1|DEBUG] PluginDriver:9583f9eb-3bc6-4c7f-8812-b596770a8493: Performing login process
2016-04-28 13:59:56,248 [1|DEBUG] PluginDriver:9583f9eb-3bc6-4c7f-8812-b596770a8493: Authenticating user tester, 2 plugins available
2016-04-28 13:59:56,248 [1|DEBUG] PluginDriver:9583f9eb-3bc6-4c7f-8812-b596770a8493: Calling 31522a54-7b6f-4867-9bd2-8aabae1b2400
2016-04-28 13:59:56,259 [1|DEBUG] vCRMAuth: Authenticate: tester
2016-04-28 13:59:56,279 [1|DEBUG] PluginLoader: Resolving dependency pGina.Plugin.vCRMAuth.XmlSerializers.dll
2016-04-28 13:59:56,280 [1|DEBUG] PluginLoader: Looking for: C:\Program Files\pGina\pGina.Plugin.vCRMAuth.XmlSerializers.dll
2016-04-28 13:59:56,280 [1|DEBUG] PluginLoader: C:\Program Files\pGina\pGina.Plugin.vCRMAuth.XmlSerializers.dll not found
2016-04-28 13:59:56,281 [1|ERROR] PluginLoader: Unable to resolve dependency: pGina.Plugin.vCRMAuth.XmlSerializers, Version=3.2.4.1, Culture=neutral, PublicKeyToken=null
2016-04-28 14:00:15,660 [1|DEBUG] PluginLoader: Resolving dependency pGina.Plugin.vCRMAuth.dll
2016-04-28 14:00:15,661 [1|DEBUG] PluginLoader: Looking for: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\pGina.Plugin.vCRMAuth.dll
2016-04-28 14:00:15,661 [1|DEBUG] PluginLoader: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\pGina.Plugin.vCRMAuth.dll not found
2016-04-28 14:00:15,662 [1|ERROR] PluginLoader: Unable to resolve dependency: pGina.Plugin.vCRMAuth, Version=3.2.4.1, Culture=neutral, PublicKeyToken=null
2016-04-28 14:00:15,863 [1|DEBUG] vCRMAuth: FileLoadException: System.IO.FileLoadException: Could not load file or assembly 'pGina.Plugin.vCRMAuth.XmlSerializers' or one of its dependencies. Array subscript out of range. (Exception from HRESULT: 0x80131508)
File name: 'pGina.Plugin.vCRMAuth.XmlSerializers' ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pGina.Core.PluginLoader.ResolvePluginDependencies(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.LoadWithPartialNameInternal(AssemblyName an, Evidence securityEvidence, StackCrawlMark& stackMark)
   at System.DirectoryServices.Interop.UnsafeNativeMethods.IAds.PutEx(Int32 lnControlCode, String bstrName, Object vProp)
   at System.DirectoryServices.PropertyValueCollection.OnClearComplete()
   at System.DirectoryServices.PropertyValueCollection.set_Value(Object value)
   at System.DirectoryServices.AccountManagement.SAMStoreCtx.AcctExpirDateToNTConverter(Principal p, String propertyName, DirectoryEntry de, String suggestedWinNTProperty, Boolean isLSAM)
   at System.DirectoryServices.AccountManagement.SAMStoreCtx.PushChangesToNative(Principal p)
   at System.DirectoryServices.AccountManagement.SDSUtils.ApplyChangesToDirectory(Principal p, StoreCtx storeCtx, GroupMembershipUpdater updateGroupMembership, NetCred credentials, AuthenticationTypes authTypes)
   at System.DirectoryServices.AccountManagement.SAMStoreCtx.Update(Principal p)
   at pGina.Plugin.vCRMAuth.PluginImpl.AuthenticateUseRecurention(SessionProperties properties, Int32 level)
```

**Comment by mdghost** [comment]
I think I found the solution (2 steps) pGina.Core.PluginLoader:


```
public static Assembly ResolvePluginDependencies(Object sender, ResolveEventArgs args)
{...
// First: Check if the requested assembly is part of the loaded assemblies
            Assembly loadedAssembly = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.FullName == args.Name);
            if (loadedAssembly != null)
            { return loadedAssembly; }
//Second: Skip xmlserializers
if (name.EndsWith(".xmlserializers", StringComparison.OrdinalIgnoreCase))
                      { return null; }
```

**Comment by nate-yocom** [comment]
I like it, pull request?

**Comment by mdghost** [comment]
Unfortunatly I can't ;D But You can put it on the beginning of ResolvePluginDependencies about line: 89 just after :
```
public static Assembly ResolvePluginDependencies(Object sender, ResolveEventArgs args)
{
            // Get the file name
            string[] fields = args.Name.Split(',');
            string name = fields[0].Trim();
            string culture = fields[2].Trim();
```
