### ISSUE TITLE
Cant login to pGina Account

### ISSUE THREAD

**Issue by rlkarthik** [pgina/pgina#306]
I cant login pGina User in the windows 8 64 bit . In the Log i Observed this is the issue

2016-03-01 16:13:27,245 [2208|25|DEBUG] LocalAccount[Ora4Treat]: SyncToLocalUser()
2016-03-01 16:13:27,263 [2208|25|ERROR] PluginDriver:76cd2828-609c-41ea-a397-c5f1a3e9cdd8: 12fa152d-a2e3-4c8d-9535-5dcd49dfcb6d Failed to process gateway for Ora4Treat message: Unexpected error while syncing user's info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: The system is not authoritative for the specified account and therefore cannot complete the operation. Please retry the operation using the provider associated with this account. If this is an online provider please use the provider's online site.

   --- End of inner exception stack trace ---
   at System.DirectoryServices.DirectoryEntry.Invoke(String methodName, Object[] args)
   at pGina.Plugin.LocalMachine.LocalAccount.SyncUserPrincipalInfo(UserPrincipal user, UserInformation info)
   at pGina.Plugin.LocalMachine.LocalAccount.SyncToLocalUser()
   at pGina.Plugin.LocalMachine.PluginImpl.AuthenticatedUserGateway(SessionProperties properties)
2016-03-01 16:13:27,263 [2208|25|DEBUG] PluginDriver:76cd2828-609c-41ea-a397-c5f1a3e9cdd8: End login chain, 1 stateful plugin(s).
2016-03-01 16:13:27,263 [2208|25|DEBUG] LdapPlugin: EndChain

**Comment by rlkarthik** [comment]
> [__]( @ #url)
![pgina](https://cloud.githubusercontent.com/assets/19838625/15931414/4ef02132-2e75-11e6-8796-1ec7d429df80.png)
