### ISSUE TITLE
Cant connect to SSL secure LDAP

### ISSUE THREAD

**Issue by dlucik** [pgina/pgina#371]
I cant connect to google ldap serer. I use convertet certyfikate (.crt _.key) to .p12

****
**** Simulated login starting: piątek, 27 marca 2020 15:24:43
**** pGina Version:  3.2.4.0
**** Enabled plugins: 
****     Authentication: LDAP
****     Authorization: 
****     Gateway: 
****     Notification: 
****
2020-03-27 15:24:43,737 [1|DEBUG] PluginDriver:966e747e-4886-46cf-91ab-4df5745b7c66: New PluginDriver created
2020-03-27 15:24:43,741 [1|DEBUG] PluginDriver:966e747e-4886-46cf-91ab-4df5745b7c66: Begin login chain, 1 stateful plugin(s).
2020-03-27 15:24:43,742 [1|DEBUG] LdapPlugin: BeginChain
2020-03-27 15:24:43,744 [1|DEBUG] LdapServer: Initializing LdapServer host(s): [ldap.google.com], port: 636, encryption = TLS_SSL, verifyCert = False
2020-03-27 15:24:43,746 [1|DEBUG] LdapServer: Timeout set to 10 seconds.
2020-03-27 15:24:43,748 [1|DEBUG] PluginDriver:966e747e-4886-46cf-91ab-4df5745b7c66: Performing login process
2020-03-27 15:24:43,754 [1|DEBUG] PluginDriver:966e747e-4886-46cf-91ab-4df5745b7c66: Authenticating user lukasz.dlucik, 1 plugins available
2020-03-27 15:24:43,755 [1|DEBUG] PluginDriver:966e747e-4886-46cf-91ab-4df5745b7c66: Calling 0f52390b-c781-43ae-bd62-553c77fa4cf7
2020-03-27 15:24:43,757 [1|DEBUG] LdapPlugin: AuthenticateUser(966e747e-4886-46cf-91ab-4df5745b7c66)
2020-03-27 15:24:43,759 [1|DEBUG] LdapPlugin: Received username: lukasz.dlucik
2020-03-27 15:24:43,761 [1|DEBUG] LdapPlugin: Attempting authentication for lukasz.dlucik
2020-03-27 15:24:43,764 [1|DEBUG] LdapServer: Attempting to bind with DN uid=lukasz.dlucik,dc=abastran,dc=com
2020-03-27 15:24:43,766 [1|DEBUG] LdapServer: Attempting bind as uid=lukasz.dlucik,dc=abastran,dc=com
2020-03-27 15:24:43,851 [1|DEBUG] LdapServer: VerifyCert(...)
2020-03-27 15:24:43,853 [1|DEBUG] LdapServer: Verifying certificate from host: ldap.google.com
2020-03-27 15:24:43,856 [1|DEBUG] LdapServer: Server certificate accepted without verification.
2020-03-27 15:24:44,555 [1|DEBUG] LdapServer: Closing LDAP connection to ldap.google.com.
2020-03-27 15:24:44,558 [1|ERROR] LdapPlugin: Exception in LDAP authentication: System.DirectoryServices.Protocols.DirectoryOperationException: The object does not exist.
   at System.DirectoryServices.Protocols.LdapConnection.BindHelper(NetworkCredential newCredential, Boolean needSetCredential)
   at pGina.Plugin.Ldap.LdapServer.Bind(NetworkCredential creds)
   at pGina.Plugin.Ldap.LdapServer.Authenticate(String uname, String password)
   at pGina.Plugin.Ldap.LdapPlugin.AuthenticateUser(SessionProperties properties)
2020-03-27 15:24:44,561 [1|ERROR] PluginDriver:966e747e-4886-46cf-91ab-4df5745b7c66: 0f52390b-c781-43ae-bd62-553c77fa4cf7 Threw an unexpected exception, assuming failure: System.DirectoryServices.Protocols.DirectoryOperationException: The object does not exist.
   at System.DirectoryServices.Protocols.LdapConnection.BindHelper(NetworkCredential newCredential, Boolean needSetCredential)
   at pGina.Plugin.Ldap.LdapServer.Bind(NetworkCredential creds)
   at pGina.Plugin.Ldap.LdapServer.Authenticate(String uname, String password)
   at pGina.Plugin.Ldap.LdapPlugin.AuthenticateUser(SessionProperties properties)
   at pGina.Core.PluginDriver.AuthenticateUser()
2020-03-27 15:24:44,567 [1|ERROR] PluginDriver:966e747e-4886-46cf-91ab-4df5745b7c66: Failed to authenticate lukasz.dlucik, Message: 
2020-03-27 15:24:44,572 [1|DEBUG] PluginDriver:966e747e-4886-46cf-91ab-4df5745b7c66: End login chain, 1 stateful plugin(s).
2020-03-27 15:24:44,575 [1|DEBUG] LdapPlugin: EndChain

**Comment by dlucik** [comment]
![image](https://user-images.githubusercontent.com/26936761/77766289-bcbd6200-703f-11ea-9acd-28cafbcc7b85.png)

**Comment by Trailingslashes** [comment]
Try changing the port to 389
